### ISSUE TITLE
[Bug]: failed to initialize XAML Diagnostics. 0x80070490: Element not found.

### ISSUE THREAD

**Issue by JahsehWalker** [TranslucentTB/TranslucentTB#1089]
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

The app was working fine till yesterday, today i turned on my Asus Tuf F15 i5 11th gen windows 11 {version 23H2, OS build: 22631.4391} and it showed the following error 
![IMG-20241109-WA0000](https://github.com/user-attachments/assets/3ace0657-5a3a-4784-bd7b-d21151404022)

### Expected results

Didn't really expected it is stop working all of a sudden 

### Actual results

"TranslucentTB has encountered a fatal error and cannot continue executing. Failed to initialize XAML Diagnostics. (0x80070490): Element not found."

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by jacksonkimball** [comment]
I found a possible work around! Right click on the app in the windows menu and click "Run as administrator" and allow and it should allow it to work! hope this helps!

**Comment by JahsehWalker** [comment]
Thanks for the reply, unfortunately that didn't work, I've already tried it. And for some reason today when I tried using that app, it worked, but later on it failed showing another error code with similar statement

**Comment by havilson** [comment]
I have the same issue.

**Comment by wuyuxuan0706** [comment]
same issue ocurred.

**Comment by 555five** [comment]
This happened to me today immediately after windows restarted after windows update installed a display adaptor -
[ Intel Corporation - Display - 31.0.101.2130 ]

Windows 23H2

**Comment by 555five** [comment]
This happened to me today immediately after windows update installed a display adapter - 
[ Intel Corporation - Display - 31.0.101.2130 ]
Once I rolled back the driver to the previous version [ 31.0.101.2127 ] the problem was resolved. 

To rollback the driver, you may follow the steps below:

Press Windows + R on the desktop screen.
Type devmgmt.msc and hit enter.
Expand the category you want and right click on the driver and select properties.
Navigate to driver tab and click on RollBack driver.

**Comment by Fadhilul** [comment]
Sam issue

**Comment by r4ian** [comment]
Same issue, running as admin didn't help. 

still happens after update to nvidia app 11.0.1.184, Geforce Game Ready driver 566.36

Win11: 23H2 22631.4460

**Comment by kwang0010** [comment]
same issue，It doesn't work after my windows update.

**Comment by 555five** [comment]
Did you guys try rolling back your display adapters to previous versions?

**Comment by crcastilho** [comment]
I'm running a newly installed Windows 11 25H2 build 26200-7309 and the same message error. Tried the portable App as well, and it did not work. Event Viewer shows 2 errors: one related to TranslucentTB.exe and the other related to explorer.exe. Below are the error transcript:
Faulting application name: TranslucentTB.exe, version: 2025.1.0.0, time stamp: 0x9c321504
Faulting module name: ProgramLog.dll, version: 0.0.0.0, time stamp: 0x219d6624
Exception code: 0xc0000409
Fault offset: 0x0000000000025a5e
Faulting process id: 0x576C
Faulting application start time: 0x1DC648FABC6568A
Faulting application path: C:\Program Files\WindowsApps\28017CharlesMilette.TranslucentTB_2025.1.0.0_x64__v826wp6bftszj\TranslucentTB.exe
Faulting module path: C:\Program Files\WindowsApps\28017CharlesMilette.TranslucentTB_2025.1.0.0_x64__v826wp6bftszj\ProgramLog.dll
Report Id: 77d32be4-a4ce-41c3-ad39-5134e97c1031
Faulting package full name: 28017CharlesMilette.TranslucentTB_2025.1.0.0_x64__v826wp6bftszj
Faulting package-relative application ID: TranslucentTB

Faulting application name: Explorer.EXE, version: 10.0.26100.7309, time stamp: 0x3bfe0367
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.26100.7309, time stamp: 0x62287fde
Exception code: 0xc000027b
Fault offset: 0x0000000000304f6f
Faulting process id: 0x59F0
Faulting application start time: 0x1DC648FB1AEFB90
Faulting application path: C:\Windows\Explorer.EXE
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: bfd27b83-cf53-42dd-9419-111061b65a13
Faulting package full name: 
Faulting package-relative application ID: 

Both event ID is 1000.

I'd appreciate any help to solve this.

**Comment by sylveon** [comment]
Please send the dump from the explorer crash.

**Comment by crcastilho** [comment]
> Please send the dump from the explorer crash.

Pardon my ignorance, but how do I do that?

**Comment by crcastilho** [comment]
Here is the dump.

https://1drv.ms/u/c/f68b1759f2287464/IQDxEXZh4X1wT4EejDTh_7AKAUBfcdxnNXCBqR73PiwbNlE?e=Yk6xgU

**Comment by sylveon** [comment]
Can you get a full dump instead of a minidump? In an admin command prompt:
```
reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpType /t REG_DWORD /d 2
```
This should enable full dumps

**Comment by crcastilho** [comment]
Link to the new dump.

https://1drv.ms/u/c/f68b1759f2287464/IQDxEXZh4X1wT4EejDTh_7AKAUBfcdxnNXCBqR73PiwbNlE?e=KMZbZm

**Comment by sylveon** [comment]
Hmmm, it's crashing with Xaml Diagnostics. Do you have other taskbar mods installed?

Can you perhaps try using [UWPSpy](https://ramensoftware.com/uwpspy) on explorer.exe and seeing if that crashes?

**Comment by crcastilho** [comment]
UWPSpy also crashed explorer. To my knowledge, I don't have any mods installed.
Here's a list of all apps I have installed.

[installed-apps.txt](https://github.com/user-attachments/files/23981894/installed-apps.txt)

**Comment by sylveon** [comment]
Interesting. The stack trace and restricted error looks like an OS issue (XAML diagnostics is failing internally during AdviseVisualTreeChange). Does this dev build help at all? https://dev.azure.com/TranslucentTB/TranslucentTB/_build/results?buildId=164&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by crcastilho** [comment]
Interesting, indeed. I reinstalled my laptop from scratch about 3 weeks ago. The same ISO I used to format and reinstall my nephew PC last week, in which TB worked just fine.
So, I downloaded the 2 portable versions from your link. The release one gets same error. The debug one lacks some DLLs for me.
https://i.imgur.com/2EUKXRc.png https://i.imgur.com/188QIvX.png https://i.imgur.com/1eKYSNo.png
P.S.: installed VS 2022 and dll problem was gone, but crashes all the same.

**Comment by mgh9** [comment]
I had the same issue, and this fixed it:
[https://github.com/TranslucentTB/TranslucentTB/issues/979#issuecomment-3480795585](url)
