### ISSUE TITLE
Make taskbar system theme when start menu opened if possible

### ISSUE THREAD

**Issue by whatHappenedToBrendanFraser** [TranslucentTB/TranslucentTB#25]

**Comment by ethanhs** [comment]
I really like this idea, thanks!

**Comment by olliethepikachu** [comment]
If we knew the class of the Start Menu (when I get a chance I'll do that), we could probably use FindWindow to tell if it's open, and potentially use MonitorFromWindow and tell what monitor it's in. As I'm not in front of a computer this is all theoretical, but when I get a chance I'll look into it.

**Comment by ethanhs** [comment]
The class is `Windows.UI.Core.CoreWindow`, which is the class name of all UWP apps. It has a title of "Start". This is very do-able.

**Comment by qwerty12** [comment]
Since this is for Windows 10 only, there's a [COM interface](http://stackoverflow.com/a/33138579) available that lets you be notified if the start menu/screen is opened. I call `IAppVisibility_IsLauncherVisible` in my personal fork of hotcorner and it works well enough for me...

**Comment by whatHappenedToBrendanFraser** [comment]
@ethanhs Sweet! Thanks.

**Comment by ethanhs** [comment]
@qwerty12 excellent thank you! That sounds like the perfect way to display things.

**Comment by qwerty12** [comment]
> Actually, I don't think that would work for multi-monitor support...

Sorry, I don't have a multi-monitor system, so I don't know what special considerations need to be taken into place. Is the idea to only change the colour of the taskbar that the start menu is open on? If that's the case, and polling for the start menu state isn't desired, then you might be able to combine the IAppVisibility notification with olliethepikachu's idea. Otherwise, getting the notification should be enough and you can manipulate all the taskbars. I think. I like IAppVisibility because it's documented, but I do understand why it's not necessarily suitable, however.

A shell hook also works to catch the start menu being created without polling (the HWND in the lParam has the title of "Cortana", which is the same title I get when I use AutoHotkey's Active Window Spy on the start menu myself). OTOH, if there's nothing wrong with polling, then I'll go back to lurking :-)

**Comment by ethanhs** [comment]
I don't like polling, as that uses more resources, a shell hook sounds nice.

**Comment by MrAksel** [comment]
Well we haven't actually seen the negative sides of polling yet. CPU still stays down, but I agree, we might start noticing it if we poll more and more functions.

**Comment by olliethepikachu** [comment]
We could use a shell hook and then poll once for the start menu to see what display it's in. As @qwerty12 said.

**Comment by ethanhs** [comment]
This also should be resolved in #33

**Comment by olliethepikachu** [comment]
Uhh, @ethanhs my PR doesn't solve this issue, but it lays the groundwork for an implementation.

**Comment by ethanhs** [comment]
Ah, your right, getting ahead of myself. :<
I'll be adding it in my refactoring.

**Comment by olliethepikachu** [comment]
Update - sorry it took so long everybody ! I've had school and such D:

I just pushed commit https://github.com/TranslucentTB/TranslucentTB/commit/b6479fd6e60ca24e1a4a08a81490cb14b45e4c57 which adds support for the `dynamic-start` option.

**Comment by ethanhs** [comment]
Thanks so much! Don't worry about the delay. I know how school can get in the way.

**Comment by ethanhs** [comment]
Okay, I just tested and it isn't working. I will see what the cause is.

**Comment by olliethepikachu** [comment]
@ethanhs How would I reproduce your observed behaviour? Or is it just that it doesn't work at all?

**Comment by olliethepikachu** [comment]
@ethanhs has now fixed this issue for him, who is using the Windows Creators' insider build. I think this feature is finished.

**Comment by ethanhs** [comment]
@olliethepikachu first of all, nothing has been merged, so I think it is too early to close it and say everythign is done. I also haven't added the requisite changes to have it work for me. I will do so today. Then we can PR the changes into develop and be finished.

**Comment by olliethepikachu** [comment]
Oh okay, sorry, I thought you'd added your changes.
		

		Get Outlook for iOS
	





On Mon, Apr 10, 2017 at 3:31 AM +0800, "Ethan" <notifications@github.com> wrote:












@olliethepikachu first of all, nothing has been merged, so I think it is too early to close it and say everythign is done. I also haven't added the requisite changes to have it work for me. I will do so today. Then we can PR the changes into develop and be finished.

**Comment by ethanhs** [comment]
No worries, and I just added the small change needed. Im going to open a PR and hopefully we can go through and review everything and then merge and close this.

**Comment by ethanhs** [comment]
This now fixed in develop!
