### ISSUE TITLE
taskbar bugs after sleep

### ISSUE THREAD

**Issue by filipwasikai** [TranslucentTB/TranslucentTB#371]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version:  newest I guess
 - Windows build number:  OS Build 1094.867
 - Steps to reproduce:  put the computer to sleep and turn it back on
 - Expected results:  the settings stay the same (clear tb)
 - Actual results:  the taskbar is on another setting (blur I think) but only on the main monitor not on the secondary
 - Other:  if I reopen the program it works again

**Comment by MrMeeb** [comment]
Also seeing this - when the PC wakes from sleep, TTB has deactivated, causing W10 default behavior. I assume this is something to do with the monitors 'disconnecting' as they go to sleep. Resolved by reloading TTB, which is not ideal

**Comment by sylveon** [comment]
This should be fixed in the latest update, available in the Store.

**Comment by willianzjy0809** [comment]
Hello, unfortunately, it is not fixed. I used windows 10 with version 21H1, OS build 19043.1348
