### ISSUE TITLE
"config.cfg" file not being read.

### ISSUE THREAD

**Issue by jinke159** [TranslucentTB/TranslucentTB#79]
The start menu is opened and the taskbar flashes once.
After the boot setting is default(blur)
I have to restart "TranslucentTB.exe", "Dynamic windows" to take effect

I do not know how I solved, but I did solve this problem, as if by adding "TranslucentTB" in 

> C:\ Users \ jk \ AppData \ Roaming \ Microsoft \ Windows \ Start Menu \ Programs \ Startup

". Lnk ", 
and in such a configuration: 
Dynamic states: Window States and (WIP) Start Menu Dynamic-ws = enable .
Perhaps also in the "TranslucentTB.lnk" set the parameters, such as a "-save". Remember not clear

**Comment by ethanhs** [comment]
I believe our move to higher update tick on this release was pre-mature. Also the boot settings is concerning, and I have experienced it myself, but I haven't been able to reproduce it.

**Comment by denosawr** [comment]
Could you post a picture of the `TranslucentTB.exe` and `config.cfg`? And, how you are running the application?

**Comment by amicraft** [comment]
The config file doesnot work. No matter which option be selected, the setting would be set to default(blur) after reboot.
Then I check the code, I find `opt.taskbar_appearance = ACCENT_NORMAL_GRADIENT;` in line 1039. Is this mean resetting the option to default blur??

**Comment by denosawr** [comment]
I think that the config file error is another issue; we'll look into it. Line 1039 is only run _after_ you quit TTB, and it sets `opt.taskbar_appearance` so that it can make the taskbar black once it exits - it's completely irrelevant, don't worry.

**Comment by denosawr** [comment]
In the meantime, could we see your config file and where it is located?

**Comment by amicraft** [comment]
config.cfg:
```
; Taskbar appearance: opaque, transparent, or blur (default).
accent=transparent

```
It is in the same folder with the exe which is located some directory like `D:\Program Files\TranslucentTB.2017.3`. The win10 OS is in C:.

**Comment by ChriscomIT** [comment]
Hey same for me. Also even when set to blurred when maximized via .cfg the TB stays transparent. Only when I set it via the .exe it works as intended. After a reboot, it is as reported not transparent at all.

Also when you set dynamic start via the .exe context menu it will not change the dynamic start value to either "true" or "false".

Config: 

`; Taskbar appearance: opaque, transparent, or blur (default).
accent=transparent

; Color and opacity of the taskbar.
color=0    ; A color in hexadecimal notation. Described in usage.md.
opacity=0    ; A value in the range 0 to 255. 255 = opaque 0 = transparent

; dynamic windows: opaque, transparent, or blur (default).
; dynamic-ws=blur
; dynamic windows can be used in conjunction with a custom color and non-zero opacity!

; dynamic start
; dynamic-start=false`

**Comment by ethanhs** [comment]
Im guessing either there is an error in how we are reading the config file, or there is some weirdness in how Windows boots. Probably the former.

**Comment by denosawr** [comment]
Could it be that when launching from regedit, TTB starts up in a different folder and cannot read the config file? @ethanhs

**Comment by charlesmilette** [comment]
If that is the case, process explorer can find the working directory

**Comment by denosawr** [comment]
We could even use this code, which is already in the executabl: ```cpp
HMODULE hModule = GetModuleHandle(NULL);
TCHAR path[MAX_PATH];
GetModuleFileName(hModule, path, MAX_PATH);```

**Comment by denosawr** [comment]
This is a temporary fix:

Open the Windows registry editor, go to HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run. You should see an entry named TranslucentTB. Double-click on it to edit it and add --config C:\Path\to\where\TranslucentTB\is\stored\config.cfg. Press OK, and reboot.

**Comment by amicraft** [comment]
My solution:
Create a shortcut in `C:\Users\[User]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` with your own parameters on it.

**Comment by jinke159** [comment]
I do not know how I solved, but I did solve this problem, as if by adding "TranslucentTB" in "C: \ Users \ jk \ AppData \ Roaming \ Microsoft \ Windows \ Start Menu \ Programs \ Startup". Lnk ", and in such a configuration:

; Dynamic states: Window States and (WIP) Start Menu
Dynamic-ws = enable
Perhaps also in the "TranslucentTB.lnk" set the parameters, such as a "-save"
Remember not clear

**Comment by jinke159** [comment]
I am through reading "Readme.md" and "usage.md", their own chaos test to solve

**Comment by denosawr** [comment]
Yes, when you put the file there, it launches running from the directory it's located in and therefore can find the config file. When using the "boot at start" menu option, it is starting the executable in a different directory and therefore it cannot find the config file. This should be fixable in the next release.

**Comment by denosawr** [comment]
Whoa, calm down! :)

The fix hasn't been released yet so we'll leave it open. When we actually release the fixed version I'll close it. Thanks for your help everyone!

**Comment by denosawr** [comment]
Update: this issue has been fixed in the latest code (in the `store` branch).

**Comment by jinke159** [comment]
Thank you very much @denosawr

**Comment by D0ublek1ll** [comment]
Is this fix available in the latest download? Or do I have to build it myself?

**Comment by ethanhs** [comment]
@D0ublek1ll you can download the latest preview release here: https://ci.appveyor.com/project/sylveon/translucenttb/branch/develop/artifacts

**Comment by insanezz** [comment]
I tried the preview release but for me it doesn't fix the issue. I still don't get a transparent taskbar + my specified color. I have to manually open the program everytime i reboot because when it auto starts it just goes back to the default blur.

**Comment by pyokorider** [comment]
Spent 2 hours to find the solution and here's what I did to fix the issue eventually
-Disable Open at boot
-Create TranslucentTB.exe shortcut
-Win+R(Run)->shell:common startup and hit Enter
-Cut/copy the shortcut to the Startup folder
-Right-click the shortcut to open Properties
-In Target box, add --clear to the end of the line (don't forget the blank). Like this
"C:\Program Files\TranslucentTB\TranslucentTB.exe" --clear

**Comment by pyokorider** [comment]
Found a solid solution eventually
-Disable Open at boot
-Create TranslucentTB.exe shortcut
-Win+R(Run)->shell:common startup and hit Enter
-Cut/copy the shortcut to the Startup folder
-Right-click the shortcut to open Properties
-In Target box, add --clear to the end of the line (don't forget the blank). Like this
"C:\Program Files\TranslucentTB\TranslucentTB.exe" --clear

**Comment by sylveon** [comment]
FYI you can edit your messages. No need to delete and resend it 4 times.

**Comment by pyokorider** [comment]
I know I can edit but I have all the time in the world :D.

**Comment by D0ublek1ll** [comment]
Its annoying ;) i got a bunch of emails because of this. Thanks for the fix though.

**Comment by pyokorider** [comment]
Jeez I forgot about that. Please accept my apologies:D
